





train loader: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25500/25500 [00:12<00:00, 1993.42it/s]
test loader: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2250/2250 [00:01<00:00, 1978.89it/s]
testing models:   0%|                                                                                                                                                              | 0/100 [00:00<?, ?it/s]

testing models:   9%|█████████████▌                                                                                                                                        | 9/100 [00:02<00:24,  3.74it/s]
Traceback (most recent call last):
  File "/export/raid1/home/kneel027/Second-Sight/scalar_experiments/scalar_LR.py", line 332, in <module>
    main()
  File "/export/raid1/home/kneel027/Second-Sight/scalar_experiments/scalar_LR.py", line 329, in main
    VM.predict_c_seperate(test)
  File "/export/raid1/home/kneel027/Second-Sight/scalar_experiments/scalar_LR.py", line 283, in predict_c_seperate
    model.load_state_dict(torch.load("scalar_space_models/model_z_" + str(i) + ".pt"))
  File "/export/raid1/home/kneel027/miniconda3/envs/ldm/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/export/raid1/home/kneel027/miniconda3/envs/ldm/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/export/raid1/home/kneel027/miniconda3/envs/ldm/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'scalar_space_models/model_z_9.pt'